apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http
      port: 80      # Port exposed by the service
      targetPort: http-backend # Port on the container
  type: ClusterIP #