apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: http
      port: 80      # Port exposed by the service
      targetPort: http-frontend # Port on the container
  type: ClusterIP # Service type, can be ClusterIP, NodePort, LoadBalancer